<?php

/**
 * @file
 * Contains event_registration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function event_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_registration module.
    case 'help.page.event_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function event_registration_theme() {
  $theme = [];
  $theme['event_registration'] = [
    'render element' => 'elements',
    'file' => 'event_registration.page.inc',
    'template' => 'event_registration',
  ];
  $theme['event_registration_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'event_registration.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function event_registration_theme_suggestions_event_registration(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#event_registration'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'event_registration__' . $sanitized_view_mode;
  $suggestions[] = 'event_registration__' . $entity->bundle();
  $suggestions[] = 'event_registration__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'event_registration__' . $entity->id();
  $suggestions[] = 'event_registration__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
