<?php

/**
 * @file
 * Contains event_registration.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\event\Entity\EventInterface;

/**
 * Implements hook_help().
 */
function event_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the event_registration module.
    case 'help.page.event_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function event_registration_theme() {
  $theme = [];
  $theme['event_registration'] = [
    'render element' => 'elements',
    'file' => 'event_registration.page.inc',
    'template' => 'event_registration',
  ];
  $theme['event_registration_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'event_registration.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function event_registration_theme_suggestions_event_registration(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#event_registration'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'event_registration__' . $sanitized_view_mode;
  $suggestions[] = 'event_registration__' . $entity->bundle();
  $suggestions[] = 'event_registration__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'event_registration__' . $entity->id();
  $suggestions[] = 'event_registration__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_type_alter().
 */
function event_registration_entity_type_alter(array &$entity_types) {
  $entity_types['event']->setLinkTemplate('event-registration-overview', '/event/{event}/registration');
  $entity_types['event']->setLinkTemplate('event-registration-list', '/event/{event}/registration/list');
  $entity_types['event']->setLinkTemplate('event-registration-mine', '/event/{event}/registration/mine');
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function event_registration_event_access(EventInterface $event, $operation, AccountInterface $account) {
  if ($operation == 'register') {
    $bundle = $event->bundle();
    $permissions = [
      'register for any event',
      'register for ' . $bundle . ' event',
    ];
    return AccessResult::allowedIfHasPermissions($account, $permissions, 'OR');
  }
  return AccessResult::neutral();
}
